---
ID: "c5af5af5-0fac-437e-9777-98b49380d385"
Parent: "5fea99db-eb6d-4559-babe-a833129af4ce"
Template: "5fea99db-eb6d-4559-babe-a833129af4ce"
Path: /sitecore/templates/Feature/BasicContent/_Base Page/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20221010T133624Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "07641493-9882-49cc-b3f0-f10584d74878"
    - ID: "8dbe4d4f-7ed4-47b2-8996-393b7d894634"
      Hint: Title
      Value: $name
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20221010T133630Z
