---
ID: "84894c45-95aa-4065-8f3a-a2559b1fba99"
Parent: "f07dbfc5-0cd4-4f7e-910b-85399acc45bd"
Template: "f07dbfc5-0cd4-4f7e-910b-85399acc45bd"
Path: /sitecore/templates/Feature/BasicContent/Section Header/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "111ff2ab-266e-4d66-bfd7-00e58bf85625"
      Hint: Text
      Value: $name
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20221012T155301Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "ca5ae6d3-53a0-4a75-b4a0-9de896db2539"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20221012T155307Z
