---
ID: "4ea7a310-6c9b-4e9c-aa27-56d535807789"
Parent: "b7f28ea6-be8a-47cc-9d28-9d5441691504"
Template: "b7f28ea6-be8a-47cc-9d28-9d5441691504"
Path: /sitecore/templates/Project/Sc102Project/Folder Types/Page Components Folder/__Standard Values
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: office/32x32/folder_window.png
- ID: "a791f095-2521-4b4d-bef9-21dda221f608"
  Hint: __Style
  Value: "font-size: 90%; font-style: italic;"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20221012T100258Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "8cf7d464-7313-49bf-9ea4-5a53bfb45ad7"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20221012T100530Z
